# Generated by Django 5.2.5 on 2025-11-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
