# Generated by Django 5.2.5 on 2025-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_employe_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
