# Generated by Django 5.2.5 on 2025-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employe_date_embauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
