# Generated by Django 5.2.5 on 2025-11-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_employe_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
