# Generated by Django 5.2.5 on 2025-11-12 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_employe_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['-date_embauche', 'nom'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterModelOptions(
            name='pointage',
            options={'ordering': ['-date', '-heure_arrivee'], 'verbose_name': 'Pointage', 'verbose_name_plural': 'Pointages'},
        ),
        migrations.AddField(
            model_name='employe',
            name='carte_id',
            field=models.CharField(blank=True, help_text='Scannez la carte pour associer cet ID', max_length=50, null=True, unique=True, verbose_name='ID Carte (RFID/NFC)'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom contact urgence'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contact_urgence_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone urgence'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contact_urgence_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat',
            field=models.FileField(blank=True, null=True, upload_to='contrats/', verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_employes/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='departement',
            field=models.CharField(max_length=100, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='etat_civil',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20, verbose_name='État civil'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nationalite',
            field=models.CharField(default='Marocaine', max_length=50, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='pays',
            field=models.CharField(default='Maroc', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_employes/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(max_length=100, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='ville',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='staff.employe', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heure_arrivee',
            field=models.TimeField(verbose_name="Heure d'arrivée"),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de départ'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heures_travaillees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Heures travaillées'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='retard_minutes',
            field=models.IntegerField(default=0, verbose_name='Retard (min)'),
        ),
    ]
