# Generated by Django 5.2.5 on 2025-11-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_employe_options_alter_pointage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
    ]
