# Generated by Django 5.2.5 on 2025-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_employe_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Congé verrouillé'),
        ),
        migrations.AddField(
            model_name='employe',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Fiche verrouillée'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Évaluation verrouillée'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Incident verrouillé'),
        ),
        migrations.AddField(
            model_name='planning',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Planning verrouillé'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Pointage verrouillé'),
        ),
    ]
