# Generated by Django 5.2.5 on 2025-12-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_conge_is_locked_employe_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='contact_urgence_nom',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='contact_urgence_relation',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='salaire',
        ),
    ]
