# Generated by Django 5.2.5 on 2025-10-30 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('etage', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reservee', 'Réservée'), ('occupee', 'Occupée'), ('sale', 'Sale (à nettoyer)'), ('en_nettoyage', 'En cours de nettoyage'), ('propre', 'Propre'), ('en_maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes_internes', models.TextField(blank=True)),
                ('date_derniere_maintenance', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'db_table': 'chambres',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacite_adultes', models.IntegerField(default=2)),
                ('capacite_enfants', models.IntegerField(default=0)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipements', models.TextField(blank=True, help_text='Liste des équipements séparés par des virgules')),
                ('image', models.ImageField(blank=True, null=True, upload_to='types_chambres/')),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambres',
                'db_table': 'types_chambres',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('probleme', models.TextField()),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='signale', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='chambres.chambre')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_signalees', to=settings.AUTH_USER_MODEL)),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenances_chambres',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.AddField(
            model_name='chambre',
            name='type_chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='chambres.typechambre'),
        ),
    ]
