# Generated by Django 5.2.5 on 2025-10-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], max_length=5)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('type_piece', models.CharField(blank=True, max_length=50)),
                ('numero_piece', models.CharField(blank=True, max_length=50)),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='pieces_identite/')),
                ('type_chambre_prefere', models.CharField(blank=True, max_length=50)),
                ('preferences_speciales', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sejour', 'Séjour'), ('incident', 'Incident'), ('reclamation', 'Réclamation'), ('compliment', 'Compliment')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='clients.client')),
            ],
            options={
                'db_table': 'historique_clients',
                'ordering': ['-date'],
            },
        ),
    ]
