# Generated by Django 5.2.5 on 2025-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Fiche verrouillée'),
        ),
        migrations.AddField(
            model_name='historiqueclient',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Fiche verrouillée'),
        ),
    ]
