# Generated by Django 5.2.5 on 2025-11-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_locked_historiqueclient_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historiqueclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
