# Generated by Django 5.2.5 on 2025-11-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_active_historiqueclient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
    ]
