# Generated by Django 5.2.5 on 2025-10-30 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambres', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reservation', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('date_checkin', models.DateTimeField(blank=True, null=True)),
                ('date_checkout', models.DateTimeField(blank=True, null=True)),
                ('nombre_adultes', models.IntegerField(default=1)),
                ('nombre_enfants', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours (check-in effectué)'), ('terminee', 'Terminée (check-out effectué)'), ('annulee', 'Annulée'), ('no_show', 'No-show (Absent)')], default='en_attente', max_length=20)),
                ('type_reservation', models.CharField(choices=[('directe', 'Réservation directe'), ('en_ligne', 'Réservation en ligne'), ('agence', 'Agence de voyage'), ('telephone', 'Téléphone')], default='directe', max_length=20)),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('demandes_speciales', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='chambres.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
