# Generated by Django 5.2.5 on 2025-10-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('manager', 'Manager/Directeur'), ('receptionniste', 'Réceptionniste'), ('resto_staff', 'Personnel Resto'), ('bar_staff', 'Personnel Bar'), ('comptable', 'Comptable/Caissier'), ('gouvernante', 'Gouvernante'), ('menage', 'Femme de chambre')], default='', max_length=20),
        ),
    ]
