# Generated by Django 5.2.5 on 2025-10-30 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie inventaire',
                'verbose_name_plural': 'Catégories inventaire',
                'db_table': 'categories_inventaire',
            },
        ),
        migrations.CreateModel(
            name='DemandeReapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('commandee', 'Commandée'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL)),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reappro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demandes_reapprovisionnement',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='InventairePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_inventaire', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventaires_physiques',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=10)),
                ('stock_maximum', models.IntegerField(default=100)),
                ('unite_mesure', models.CharField(default='unité', max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emplacement', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='inventaire.categorieinventaire')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement inventaire'), ('perte', 'Perte/Casse')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('bon_livraison', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='inventaire.produit')),
            ],
            options={
                'db_table': 'mouvements_stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='LigneDemandeReapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.IntegerField()),
                ('quantite_recue', models.IntegerField(default=0)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventaire.demandereapprovisionnement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.produit')),
            ],
            options={
                'db_table': 'lignes_demandes_reappro',
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('manque_produit', 'Manque de produit'), ('materiel_casse', 'Matériel cassé'), ('probleme_chambre', 'Problème chambre'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='ouvert', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='chambres.chambre')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.produit')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_faits', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signalements',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventairePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField()),
                ('quantite_physique', models.IntegerField(blank=True, null=True)),
                ('ecart', models.IntegerField(default=0)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventaire.inventairephysique')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.produit')),
            ],
            options={
                'db_table': 'lignes_inventaires_physiques',
                'unique_together': {('inventaire', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='DotationChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_standard', models.IntegerField()),
                ('frequence_renouvellement', models.CharField(help_text='ex: Quotidien, Hebdomadaire', max_length=50)),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotations', to='chambres.typechambre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.produit')),
            ],
            options={
                'db_table': 'dotations_chambres',
                'unique_together': {('type_chambre', 'produit')},
            },
        ),
    ]
