# Generated by Django 5.2.5 on 2025-11-03 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('chambres_total', models.PositiveIntegerField()),
                ('chambres_occupees', models.PositiveIntegerField()),
                ('taux_occupation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reservations_nouvelles', models.PositiveIntegerField(default=0)),
                ('reservations_annulees', models.PositiveIntegerField(default=0)),
                ('no_show', models.PositiveIntegerField(default=0)),
                ('ca_hebergement', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ca_restauration', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ca_bar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ca_autres', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ca_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revpar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('clients_nouveaux', models.PositiveIntegerField(default=0)),
                ('clients_recurrents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rapport Journalier',
                'verbose_name_plural': 'Rapports Journaliers',
                'ordering': ['-date'],
            },
        ),
    ]
