# Generated by Django 5.2.5 on 2025-11-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='ca_autres',
        ),
    ]
