# Generated by Django 5.2.5 on 2025-10-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, verbose_name='Groupe')),
                ('cle', models.CharField(max_length=50, verbose_name='Clé')),
                ('valeur', models.TextField(max_length=1024, verbose_name='Valeur')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Variable globale',
                'verbose_name_plural': 'Variables globales',
                'ordering': ('group', 'cle'),
                'indexes': [models.Index(fields=['group', 'cle'], name='parametrage_group_0d510f_idx')],
                'unique_together': {('group', 'cle')},
            },
        ),
    ]
