# Generated by Django 5.2.5 on 2025-10-30 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('type_service', models.CharField(choices=[('resto', 'Restaurant'), ('bar', 'Bar')], max_length=10)),
                ('capacite', models.IntegerField(default=4)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('reservee', 'Réservée')], default='libre', max_length=20)),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CategorieMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_service', models.CharField(choices=[('resto', 'Restaurant'), ('bar', 'Bar')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'categories_menu',
                'ordering': ['type_service', 'ordre_affichage'],
                'unique_together': {('nom', 'type_service')},
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('servie', 'Servie'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('type_service', models.CharField(choices=[('resto', 'Restaurant'), ('bar', 'Bar')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.client')),
                ('serveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_servies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='ProduitMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('type_service', models.CharField(choices=[('resto', 'Restaurant'), ('bar', 'Bar')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits_menu/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='resto.categoriemenu')),
            ],
            options={
                'db_table': 'produits_menu',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resto.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resto.produitmenu')),
            ],
            options={
                'db_table': 'commande_items',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='resto.CommandeItem', to='resto.produitmenu'),
        ),
        migrations.AddField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='resto.table'),
        ),
    ]
